# Generated by Django 5.2.17 on 2026-10-05 08:22

import django.contrib.postgres.fields
import django.db.models.deletion
import django.db.models.functions.datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('api', '0007_password_change_verification'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserAccount',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('email', models.CharField(max_length=255, unique=True)),
                ('password_hash', models.CharField(max_length=255)),
                ('role', models.CharField(max_length=20)),
                ('is_temporary_password', models.BooleanField(blank=True, null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'users',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ConversationPreference',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('target_type', models.CharField(max_length=20)),
                ('target_id', models.PositiveIntegerField()),
                ('pinned', models.BooleanField(default=False)),
                ('notification_preference', models.CharField(default='All messages', max_length=30)),
                ('updated_at', models.DateTimeField(db_default=django.db.models.functions.datetime.Now())),
            ],
            options={
                'db_table': 'conversation_preferences',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DoctorNote',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('text', models.TextField()),
                ('created_at', models.DateTimeField(blank=True, db_default=django.db.models.functions.datetime.Now(), null=True)),
            ],
            options={
                'db_table': 'doctor_notes',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DoctorPatientReminder',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('enabled', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(db_default=django.db.models.functions.datetime.Now())),
            ],
            options={
                'db_table': 'doctor_patient_reminders',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DoctorProfile',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('specialty', models.CharField(blank=True, max_length=255, null=True)),
                ('initials', models.CharField(blank=True, max_length=10, null=True)),
                ('display_color', models.CharField(blank=True, max_length=50, null=True)),
                ('clinic', models.CharField(blank=True, max_length=255, null=True)),
                ('about', models.TextField(blank=True, null=True)),
                ('license', models.CharField(blank=True, max_length=255, null=True)),
                ('phone', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'doctor_profiles',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='LifestyleLog',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('type', models.CharField(max_length=20)),
                ('date', models.DateField()),
                ('time', models.CharField(max_length=10)),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('detail', models.TextField(blank=True, null=True)),
                ('extra', models.TextField(blank=True, null=True)),
                ('payload', models.JSONField(blank=True, null=True)),
            ],
            options={
                'db_table': 'lifestyle_logs',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MonitoringHistoryEpisode',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('care_focus', models.CharField(max_length=255)),
                ('started_at', models.DateField(blank=True, null=True)),
                ('ended_at', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'monitoring_history',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MonitoringRelationship',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('visibility', models.CharField(blank=True, max_length=50, null=True)),
                ('selected_doctor_ids', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), blank=True, null=True, size=None)),
            ],
            options={
                'db_table': 'monitoring_relationships',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PasswordChangeVerification',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('code_hash', models.CharField(max_length=255)),
                ('requested_at', models.DateTimeField()),
                ('expires_at', models.DateTimeField()),
                ('attempts', models.PositiveSmallIntegerField(default=0)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'password_change_verifications',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PatientActivityType',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(db_default=django.db.models.functions.datetime.Now())),
            ],
            options={
                'db_table': 'patient_activity_types',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PatientMessage',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('sender_role', models.CharField(blank=True, max_length=20, null=True)),
                ('text', models.TextField()),
                ('is_important', models.BooleanField(blank=True, null=True)),
                ('created_at', models.DateTimeField(blank=True, db_default=django.db.models.functions.datetime.Now(), null=True)),
            ],
            options={
                'db_table': 'messages',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PatientProfile',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('unique_id', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('phone', models.CharField(blank=True, max_length=50, null=True)),
                ('home_address', models.TextField(blank=True, null=True)),
                ('emergency_contact', models.CharField(blank=True, max_length=255, null=True)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('weight_lbs', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('height_inches', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('care_focus', models.CharField(blank=True, max_length=255, null=True)),
                ('patient_type', models.CharField(blank=True, max_length=50, null=True)),
                ('status', models.CharField(blank=True, max_length=50, null=True)),
                ('priority', models.CharField(blank=True, max_length=20, null=True)),
                ('follow_up_date', models.DateField(blank=True, null=True)),
                ('monitoring_active', models.BooleanField(blank=True, null=True)),
            ],
            options={
                'db_table': 'patient_profiles',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PersonalGoal',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('category', models.CharField(blank=True, max_length=100, null=True)),
                ('target', models.CharField(blank=True, max_length=255, null=True)),
                ('frequency', models.CharField(blank=True, max_length=50, null=True)),
                ('status', models.CharField(blank=True, max_length=20, null=True)),
                ('progress_percent', models.IntegerField(blank=True, null=True)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('review_date', models.DateField(blank=True, null=True)),
                ('instructions', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'personal_goals',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ProviderGoal',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('category', models.CharField(blank=True, max_length=100, null=True)),
                ('target', models.CharField(blank=True, max_length=255, null=True)),
                ('frequency', models.CharField(blank=True, max_length=50, null=True)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('review_date', models.DateField(blank=True, null=True)),
                ('instructions', models.TextField(blank=True, null=True)),
                ('status', models.CharField(blank=True, max_length=20, null=True)),
                ('evaluation_type', models.CharField(blank=True, max_length=50, null=True)),
                ('target_value', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True)),
                ('target_unit', models.CharField(blank=True, max_length=50, null=True)),
                ('metric_key', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'provider_goals',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TeamMessage',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('text', models.TextField()),
                ('is_important', models.BooleanField(blank=True, null=True)),
                ('created_at', models.DateTimeField(blank=True, db_default=django.db.models.functions.datetime.Now(), null=True)),
            ],
            options={
                'db_table': 'team_messages',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AccountPreference',
            fields=[
                ('user', models.OneToOneField(db_column='user_id', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, related_name='account_preferences', serialize=False, to='api.useraccount')),
                ('theme', models.CharField(default='system', max_length=20)),
                ('accent', models.CharField(default='teal', max_length=20)),
                ('text_size', models.CharField(default='normal', max_length=20)),
                ('language', models.CharField(default='English', max_length=20)),
                ('default_patient_type', models.CharField(default='Out-patient', max_length=50)),
                ('default_follow_up_days', models.SmallIntegerField(default=7)),
                ('default_visibility', models.CharField(default='Assigned Only', max_length=50)),
                ('notify_dashboard', models.BooleanField(default=True)),
                ('notify_messages', models.BooleanField(default=True)),
                ('notify_reminders', models.BooleanField(default=True)),
                ('notify_activity', models.BooleanField(default=True)),
                ('notify_daily_reminder', models.BooleanField(default=True)),
                ('notify_message_alerts', models.BooleanField(default=True)),
                ('notify_weekly_summary', models.BooleanField(default=False)),
                ('notify_goal_reminders', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(db_default=django.db.models.functions.datetime.Now())),
            ],
            options={
                'db_table': 'account_preferences',
                'managed': False,
            },
        ),
    ]
